[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
flux_betting = "6HaQcudkjjPCn3wP7iSV9HKwhLSN63kLinqVLPBVPoVb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./tests/localwallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
